rbac:
  create: true
controller:
  replicaCount: 2
  publishService:
    enabled: true
  # metrics:
  #   enabled: true
    # serviceMonitor:
    #   enabled: true
    #   namespace: prometheus-operator
    #   additionalLabels:
    #     release: prometheus-operator

  # Kubesec Hardening
  # resources:
  #   limits:
  #     cpu: 1500m
  #     memory: 1Gi
  #   requests:
  #     cpu: 1500m
  #     memory: 1Gi

  config:
    # Modsecurity WAF
    # enable-modsecurity: "true"
    # enable-owasp-modsecurity-crs: "true"

    # 2. Basic Configuration

    ## CIS Nginx Configuration 2.1.3 - Ensure modules with gzip functionality are disabled
    use-gzip: "false"

    ## CIS Nginx Configuration 2.4.3 - Keepalive Timeout <= 10s
    keep-alive: "10"
    upstream-keepalive-timeout: "10"

    ## CIS Nginx Configuration 2.4.4 - Send Timeout <= 10s
    proxy-send-timeout: "10"

    ## CIS Nginx Configuration 2.5.1 - Deactivate server tokens
    server-tokens: "false"

    ## CIS Nginx Configuration 2.5.2 - Remove nginx reference - Intercept errors and send to a custom location
    http-snippet: |
      # CIS Nginx Configuration 5.2.4 - Ensure the number of connections per IP address is limited (1000 per IP)
      limit_conn_zone $binary_remote_addr zone=limitperip:50m;
      server {
        limit_conn limitperip 1000;
      }

      # CIS Nginx Configuration 5.2.5 - Ensure rate limits by IP address are set (100r /s by IP)
      limit_req_zone $binary_remote_addr zone=ratelimit:50m rate=100r/s;
      server {
        location / {
          limit_req zone=ratelimit burst=150 nodelay;
        }
      }

    # CIS Nginx Configuration 2.5.2 - Remove nginx reference from errors response
    location-snippet: |
      subs_filter "<hr><center>nginx</center>" "" gi;

    server-snippet: |
      # CIS Nginx Configuration 2.5.3 - Disallow hidden files
      location ~ /\.(?!well\-known\/acme\-challenge) { deny all; return 404 "He that breaks a thing to find out what it is has left the path of wisdom."; }

      # CIS Nginx Configuration 5.1.2 - Ensure only whitelisted HTTP methods are allowed
      if ($request_method !~ ^(GET|HEAD|POST|OPTIONS|PUT|PATCH|DELETE)$) { return 444; }

      # CIS Nginx Configuration 5.3 - Browser security headers
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options "nosniff";
      add_header X-Xss-Protection "1; mode=block";
      add_header Referrer-Policy "no-referrer";

    ## CIS Nginx Configuration 2.5.4 - Hide Headers to avoid Information Exposure
    hide-headers: Server,X-Powered-By

    # 3. Logging

    ## CIS Nginx Configuration 3.1 Ensure detailed logging is enabled
    log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status":$status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" }'
    enable-access-log-for-default-backend: "true"

    # CIS Nginx Configuration 3.7 - Ensure proxies pass source IP information
    use-forwarded-headers: "true"
    forwarded-for-header: "X-Forwarded-For"
    compute-full-forwarded-for: "true"
    # proxy-real-ip-cidr: "130.211.0.0/22,35.191.0.0/16"

    # 4. Encryption

    # CIS Nginx Configuration 4.1.1 - Ensure HTTP is redirected to HTTPS
    ssl-redirect: "true"

    # CIS Nginx Configuration 4.1.4 - Ensure only modern TLS protocols are used
    ssl-protocols: "TLSv1.2 TLSv1.3"

    # CIS Nginx Configuration 4.1.5 - Disable weak ciphers
    ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384EECDH+AESGCM:EDH+AESGCM"
    ssl-dh-param: "nginx-ingress/nginx-ingress-ssl-dh-param"

    # CIS Nginx Configuration 4.1.7 - Ensure Online Certificate Status Protocol (OCSP) stapling is enabled
    enable-ocsp: "true"

    # CIS Nginx Configuration 4.1.8 - Ensure HTTP Strict Transport Security (HSTS) is enabled
    # hsts: "true"
    # hsts-include-subdomains: "true"
    # hsts-max-age: "15724800"

    # CIS Nginx Configuration 4.1.12 - Ensure your domain is preloaded (not enforced)
    # hsts-preload: "false"

    # CIS Nginx Configuration 4.1.13 - Ensure session resumption is disabled to enable perfect forward security
    ssl-session-tickets: "false"

defaultBackend:
  enabled: false
