apiVersion: batch/v1
kind: CronJob
metadata:
  name: bloom
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bloom
            image: ghcr.io/dataforgoodfr/bloom:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure
